# Generated by Django 4.1.3 on 2023-09-06 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxonomiaExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Ninguno"),
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("success", "Success"),
                            ("danger", "Danger"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                            ("light", "Light"),
                            ("dark", "Dark"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("mostrar_en_panel", models.BooleanField(blank=True, default=False)),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hijos",
                        to="app_catalogo.taxonomiaexpediente",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
    ]
