# Generated by Django 4.1.3 on 2023-09-09 18:00

import app_catalogo.uma.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BootstrapColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("clase_color", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="CuantiaBasica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salario_inicio", models.DecimalField(decimal_places=4, max_digits=6)),
                ("salario_fin", models.DecimalField(decimal_places=4, max_digits=6)),
                (
                    "porcentaje_de_cuantia_basica",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "porcentaje_de_incremento_anual",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
            ],
            options={
                "ordering": ["salario_inicio", "salario_fin"],
            },
        ),
        migrations.CreateModel(
            name="CuentaPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuenta_de_pago", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["cuenta_de_pago"],
            },
        ),
        migrations.CreateModel(
            name="EstadoCivil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado_civil", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["estado_civil"],
            },
        ),
        migrations.CreateModel(
            name="EstatusPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estatus_de_pago", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["estatus_de_pago"],
            },
        ),
        migrations.CreateModel(
            name="FactorEdad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edad", models.PositiveSmallIntegerField()),
                ("factor_de_edad", models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                "ordering": ["edad"],
            },
        ),
        migrations.CreateModel(
            name="MedioActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medio", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["medio"],
            },
        ),
        migrations.CreateModel(
            name="RecursoExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido_paterno", models.CharField(blank=True, max_length=100)),
                ("apellido_materno", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["nombre", "apellido_paterno", "apellido_materno"],
            },
        ),
        migrations.CreateModel(
            name="TipoActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_de_actividad", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["tipo_de_actividad"],
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_de_documento", models.CharField(max_length=50)),
                ("visible_para_usuario", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["tipo_de_documento"],
            },
        ),
        migrations.CreateModel(
            name="UMA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "año",
                    models.PositiveSmallIntegerField(
                        default=app_catalogo.uma.models.getyear, unique=True
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "ordering": ["-año"],
            },
        ),
        migrations.CreateModel(
            name="TaxonomiaExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("mostrar_en_panel", models.BooleanField(blank=True, default=False)),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="app_catalogo.bootstrapcolor",
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hijos",
                        to="app_catalogo.taxonomiaexpediente",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="EstatusActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estatus_de_la_actividad", models.CharField(max_length=50)),
                ("mostrar_en_panel", models.BooleanField(blank=True, default=False)),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="app_catalogo.bootstrapcolor",
                    ),
                ),
            ],
            options={
                "ordering": ["estatus_de_la_actividad"],
            },
        ),
    ]
