# Generated by Django 4.1.3 on 2023-09-27 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.TextField()),
                ("creado_por", models.TextField(blank=True, max_length=250)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("actualizado_por", models.TextField(blank=True, max_length=250)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion", "-fecha_actualizacion"],
            },
        ),
    ]
