# Generated by Django 4.1.3 on 2023-09-06 02:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_catalogo", "0001_initial"),
        ("zend_django", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contraseña", models.CharField(max_length=255)),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        verbose_name="Fecha de nacimiento",
                    ),
                ),
                ("CURP", models.CharField(blank=True, max_length=18)),
                ("RFC", models.CharField(blank=True, max_length=13)),
                ("NSS", models.CharField(blank=True, max_length=15)),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("Casado", "Casado"),
                            ("Divorciado", "Divorciado"),
                            ("Separado", "Separado"),
                            ("Soltero", "Soltero"),
                            ("UnionLibre", "Unión Libre"),
                            ("Viudo", "Viudo"),
                        ],
                        default="Casado",
                        max_length=15,
                    ),
                ),
                ("conyuge", models.CharField(blank=True, max_length=150)),
                (
                    "clinica",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Clínica"
                    ),
                ),
                (
                    "subdelegacion",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Subdelegación"
                    ),
                ),
                ("empresa", models.CharField(blank=True, max_length=150)),
                (
                    "telefono_oficina",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Teléfono de oficina"
                    ),
                ),
                (
                    "otro_telefono",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Otro teléfono"
                    ),
                ),
                ("afore_actual", models.CharField(blank=True, max_length=50)),
                (
                    "fecha_afore_actual",
                    models.DateField(blank=True, default=datetime.date.today),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "obs_semanas_cotizadas",
                    models.TextField(blank=True, verbose_name="Semanas Cotizadas"),
                ),
                (
                    "obs_homonimia",
                    models.TextField(blank=True, verbose_name="Homonimia"),
                ),
                (
                    "obs_duplicidad",
                    models.TextField(blank=True, verbose_name="Duplicidad"),
                ),
            ],
            options={
                "ordering": [
                    "userprofile__user__last_name",
                    "userprofile__apellido_materno",
                    "userprofile__user__first_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(blank=True, max_length=100)),
                (
                    "numero_exterior",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="No. Exterior"
                    ),
                ),
                (
                    "numero_interior",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="No. Interior"
                    ),
                ),
                ("codigo_postal", models.CharField(blank=True, max_length=5)),
                ("colonia", models.CharField(blank=True, max_length=100)),
                (
                    "municipio",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Alcaldía o Municipio"
                    ),
                ),
                ("estado", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concepto", models.CharField(max_length=250)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=7)),
                ("fecha_de_pago", models.DateTimeField(blank=True, null=True)),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de Pago"),
                            ("pagado", "Pagado"),
                            ("verificado", "Pagado y Verificado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "cuenta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("daniel azteca", "Daniel Azteca"),
                            ("daniel banamex", "Daniel Banamex"),
                            ("sosa del bosque", "Sosa del Bosque"),
                        ],
                        default="efectivo",
                        max_length=50,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="app_cliente.cliente",
                    ),
                ),
            ],
            options={
                "ordering": ["-estatus", "fecha_de_pago", "pk"],
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="domicilio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cliente",
                to="app_cliente.direccion",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="gestor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_gestionados",
                to="zend_django.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_asignados",
                to="zend_django.userprofile",
                verbose_name="Ejecutivo",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clientes",
                to="app_catalogo.taxonomiaexpediente",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="userprofile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="zend_django.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="Acuerdo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=250)),
                ("acuerdo", models.TextField()),
                ("aceptado", models.BooleanField(default=False)),
                (
                    "ip",
                    models.GenericIPAddressField(
                        null=True, verbose_name="IP de aceptación"
                    ),
                ),
                (
                    "fechaHora",
                    models.DateTimeField(null=True, verbose_name="Fecha de Aceptación"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acuerdos",
                        to="app_cliente.cliente",
                    ),
                ),
            ],
            options={
                "ordering": ["titulo", "aceptado", "fechaHora"],
            },
        ),
    ]
