# Generated by Django 4.1.3 on 2023-09-13 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zend_django", "0001_initial"),
        ("app_catalogo", "0001_initial"),
        ("app_cliente", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="gestor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_gestionados",
                to="zend_django.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientes_asignados",
                to="zend_django.userprofile",
                verbose_name="Ejecutivo",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clientes",
                to="app_catalogo.taxonomiaexpediente",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="userprofile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="zend_django.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="acuerdo",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acuerdos",
                to="app_cliente.cliente",
            ),
        ),
    ]
