from .bootstrapColor.models import BootstrapColor
from .cuantiaBasica.models import CuantiaBasica
from .cuentaPago.models import CuentaPago
from .estadoCivil.models import EstadoCivil
from .estatusActividad.models import EstatusActividad
from .estatusPago.models import EstatusPago
from .factorEdad.models import FactorEdad
from .medioActividad.models import MedioActividad
from .recursoExterno.models import RecursoExterno
from .taxonomiaExpediente.models import TaxonomiaExpediente
from .tipoActividad.models import TipoActividad
from .tipoDocumento.models import TipoDocumento
from .uma.models import UMA
from .tipoParametro.models import TipoParametro
