# Generated by Django 4.1.3 on 2023-09-13 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_catalogo", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametroUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seccion", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("valor_default", models.TextField(blank=True)),
                ("es_multiple", models.BooleanField(default=False)),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="app_catalogo.tipoparametro",
                    ),
                ),
            ],
            options={
                "ordering": ["seccion", "nombre"],
                "unique_together": {("seccion", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apellido_materno", models.CharField(blank=True, max_length=50)),
                ("telefono", models.CharField(blank=True, max_length=10)),
                ("celular", models.CharField(blank=True, max_length=10)),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="what's App"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["telefono", "celular", "whatsapp"],
            },
        ),
        migrations.CreateModel(
            name="MenuOpc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("vista", models.CharField(blank=True, max_length=50)),
                ("posicion", models.PositiveSmallIntegerField()),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hijos",
                        to="zend_django.menuopc",
                    ),
                ),
                (
                    "permisos_requeridos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="El usuario que tenga almenos uno de los permisos seleccionados tendra acceso a la opcion del menú",
                        related_name="opc_menu",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "ordering": ["posicion", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ParametroUsuarioValor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.TextField()),
                (
                    "parametro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="zend_django.parametrousuario",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "parametro", "valor"],
                "unique_together": {("user", "parametro")},
            },
        ),
        migrations.CreateModel(
            name="ParametroSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seccion", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("nombre_para_mostrar", models.CharField(max_length=100)),
                ("valor", models.TextField()),
                ("es_multiple", models.BooleanField(default=False)),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="app_catalogo.tipoparametro",
                    ),
                ),
            ],
            options={
                "ordering": ["seccion", "nombre_para_mostrar"],
                "unique_together": {("seccion", "nombre")},
            },
        ),
    ]
